#!/usr/bin/env node

require = require("esm")(module); // eslint-disable-line no-global-assign
const main = require("./esm-main").default;
const asyncMainWrap = require("../../../lib/asyncMainWrap");

asyncMainWrap(main)();
