#!/usr/bin/env node

const main = require("./customErrorOutputProcessError-main");
const asyncMainWrap = require("../../../lib/asyncMainWrap");

asyncMainWrap(main, {
  processError: err => {
    err.customOutput = `NotQuite${err.name}: ${err.message}`;
    return err;
  }
})();
